# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Keep-Calm
tagline:          Crowdsourced anti-bullying chrome extension
url:              /
paginate:         1
baseurl:          http://gavra0.github.io/keep-calm/
author:
  name:           Ivan Gavrilovic / Tiziano Signo

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
